Repository SAP/terraform-provider-btp, pull requests merged in 2023-06, with the labels that each got.

#201 fix: issue form links
  README.md
Labels: bug

#199 chore: add CII badge
  README.md
Labels: documentation

#198 chore: finalize security setup
  .github/workflows/codeql.yml
  README.md
Labels: enhancement

#205 fix(docs): spelling
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
  docs/data-sources/directory.md
  docs/data-sources/directory_entitlements.md
  docs/data-sources/directory_role_collection.md
  docs/data-sources/directory_role_collections.md
  docs/data-sources/directory_user.md
  docs/data-sources/globalaccount.md
  docs/data-sources/globalaccount_entitlements.md
  docs/data-sources/globalaccount_role_collection.md
  docs/data-sources/globalaccount_role_collections.md
  docs/data-sources/globalaccount_roles.md
  docs/data-sources/globalaccount_user.md
  docs/data-sources/subaccount_entitlements.md
  docs/data-sources/subaccount_role_collection.md
  docs/data-sources/subaccount_role_collections.md
  docs/data-sources/subaccount_user.md
  docs/data-sources/subaccount_users.md
  docs/data-sources/whoami.md
  docs/resources/directory.md
  docs/resources/globalaccount_resource_provider.md
  docs/resources/globalaccount_role_collection_assignment.md
  docs/resources/subaccount.md
  docs/resources/subaccount_environment_instance.md
  examples/resources/btp_subaccount/resource.tf
  examples/resources/btp_subaccount_environment_instance/resource.tf
  internal/provider/datasource_directory.go
  internal/provider/datasource_directory_entitlements.go
  internal/provider/datasource_directory_role_collection.go
  internal/provider/datasource_directory_role_collections.go
  internal/provider/datasource_directory_user.go
  internal/provider/datasource_globalaccount.go
  internal/provider/datasource_globalaccount_entitlements.go
  internal/provider/datasource_globalaccount_role_collection.go
  internal/provider/datasource_globalaccount_role_collections.go
  internal/provider/datasource_globalaccount_roles.go
  internal/provider/datasource_globalaccount_user.go
  internal/provider/datasource_subaccount_entitlements.go
  internal/provider/datasource_subaccount_role_collection.go
  internal/provider/datasource_subaccount_role_collections.go
  internal/provider/datasource_subaccount_user.go
  internal/provider/datasource_subaccount_users.go
  internal/provider/datasource_whoami.go
  internal/provider/resource_directory.go
  internal/provider/resource_globalaccount_resource_provider.go
  internal/provider/resource_globalaccount_role_collection_assignment.go
Labels: documentation

#197 feat: test of datasource subaccounts
  docs/data-sources/subaccounts.md
  internal/provider/datasource_subaccounts.go
  internal/provider/datasource_subaccounts_test.go
  internal/provider/fixtures/datasource_subaccounts.all.yaml
Labels: enhancement

#207 fix: developer documentation
  DEVELOPER.md
  docs/index.md
  examples/provider/provider.tf
Labels: bug

#209 Chore: Best practices
  README.md
  docs/index.md
  templates/index.md.tmpl
Labels: documentation

#208 chore: additions to workflows
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/codeql.yml
Labels: enhancement

#210 feat(workflow): lint for semantic PRs
  .github/workflows/semantic-pr.yml
Labels: enhancement

#217 test: for resource_globalaccount_role_collection_assignment
  docs/resources/globalaccount_role_collection_assignment.md
  internal/provider/fixtures/resource_globalaccount_role_collection_assignment.yaml
  internal/provider/fixtures/resource_globalaccount_role_collection_assignment_with_origin.yaml
  internal/provider/resource_globalaccount_role_collection_assignment.go
  internal/provider/resource_globalaccount_role_collection_assignment_test.go
Labels: enhancement

#219 fix: error handling
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/facade_accounts_available_environment.go
  internal/btpcli/facade_accounts_available_region.go
  internal/btpcli/facade_accounts_directory.go
  internal/btpcli/facade_accounts_entitlement.go
  internal/btpcli/facade_accounts_environment_instance.go
  internal/btpcli/facade_accounts_global_account.go
  internal/btpcli/facade_accounts_label.go
  internal/btpcli/facade_accounts_resource_provider.go
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subscription.go
  internal/btpcli/facade_security_app.go
  internal/btpcli/facade_security_role.go
  internal/btpcli/facade_security_role_collection.go
  internal/btpcli/facade_security_trust.go
  internal/btpcli/facade_security_user.go
  internal/btpcli/facade_services_binding.go
  internal/btpcli/facade_services_broker.go
  internal/btpcli/facade_services_instance.go
  internal/btpcli/facade_services_offering.go
  internal/btpcli/facade_services_plan.go
  internal/btpcli/facade_services_platform.go
  internal/btpcli/helper.go
  internal/provider/datasource_subaccount_test.go
  internal/provider/fixtures/datasource_subaccount.err_subaccount_doesnt_exist.yaml
  internal/provider/fixtures/resource_globalaccount_role_collection_assignment.yaml
  internal/provider/fixtures/resource_globalaccount_role_collection_assignment_with_origin.yaml
  internal/provider/resource_directory.go
  internal/provider/resource_globalaccount_role_collection_assignment_test.go
  internal/provider/resource_globalaccount_trust_configuration_test.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_environment_instance.go
Labels: bug

#222 refactor(facade_service_instance): simplify code
  internal/btpcli/facade_services_instance_test.go
Labels: enhancement

#223 docs: use less abbreviations
  docs/data-sources/directory.md
  docs/data-sources/globalaccount.md
  docs/data-sources/subaccount.md
  docs/data-sources/subaccounts.md
  docs/resources/directory.md
  docs/resources/subaccount.md
  internal/provider/datasource_directory.go
  internal/provider/datasource_globalaccount.go
  internal/provider/datasource_subaccount.go
  internal/provider/datasource_subaccounts.go
  internal/provider/resource_directory.go
  internal/provider/resource_subaccount.go
Labels: documentation

#221 feat: label support for directories
  docs/resources/directory.md
  internal/btpcli/facade_accounts_directory.go
  internal/provider/fixtures/resource_directory.parent_directory.yaml
  internal/provider/resource_directory.go
  internal/tfutils/tfutils.go
Labels: enhancement

#225 feat: subaccount labels
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
  internal/provider/resource_subaccount.go
  internal/tfutils/tfutils.go
Labels: enhancement

#220 docs: data-source documentation improvement
  docs/data-sources/directory.md
  docs/data-sources/directory_entitlements.md
  docs/data-sources/directory_labels.md
  docs/data-sources/directory_role.md
  docs/data-sources/directory_role_collection.md
  docs/data-sources/directory_role_collections.md
  docs/data-sources/directory_roles.md
  docs/data-sources/directory_user.md
  docs/data-sources/directory_users.md
  docs/data-sources/globalaccount.md
  docs/data-sources/globalaccount_entitlements.md
  docs/data-sources/globalaccount_role_collection.md
  docs/data-sources/globalaccount_role_collections.md
  docs/data-sources/subaccount_role.md
  docs/data-sources/subaccount_role_collection.md
  docs/data-sources/subaccount_role_collections.md
  internal/provider/datasource_directory.go
  internal/provider/datasource_directory_entitlements.go
  internal/provider/datasource_directory_labels.go
  internal/provider/datasource_directory_role.go
  internal/provider/datasource_directory_role_collection.go
  internal/provider/datasource_directory_role_collections.go
  internal/provider/datasource_directory_roles.go
  internal/provider/datasource_directory_user.go
  internal/provider/datasource_directory_users.go
  internal/provider/datasource_globalaccount.go
  internal/provider/datasource_globalaccount_entitlements.go
  internal/provider/datasource_globalaccount_role_collection.go
  internal/provider/datasource_globalaccount_role_collections.go
  internal/provider/datasource_subaccount_role.go
  internal/provider/datasource_subaccount_role_collection.go
  internal/provider/datasource_subaccount_role_collections.go
  internal/provider/helper_doc_values_format.go
  internal/provider/helper_doc_values_format_test.go
Labels: documentation

#226 test: for resource_directory_role_collection_assignment
  docs/resources/directory_role_collection_assignment.md
  internal/provider/fixtures/resource_directory_role_collection_assignment.yaml
  internal/provider/fixtures/resource_directory_role_collection_assignment_with_origin.yaml
  internal/provider/resource_directory_role_collection_assignment.go
  internal/provider/resource_directory_role_collection_assignment_test.go
Labels: enhancement

#227 feat(workflow): automated release notes
  .github/release.yml
Labels: ignore-for-release

#236 fix: escaped the pipe symbol in the description in the format helper
  internal/provider/helper_doc_values_format.go
  internal/provider/helper_doc_values_format_test.go
Labels: documentation

#239 docs: documentation data sources
  docs/data-sources/globalaccount.md
  docs/data-sources/regions.md
  docs/data-sources/subaccount.md
  docs/data-sources/subaccount_entitlements.md
  docs/data-sources/subaccount_environment_instance.md
  docs/data-sources/subaccount_environment_instances.md
  docs/data-sources/subaccount_environments.md
  docs/data-sources/subaccount_labels.md
  docs/data-sources/subaccount_role_collections.md
  docs/data-sources/subaccount_roles.md
  docs/data-sources/subaccount_trust_configuration.md
  docs/data-sources/subaccount_trust_configurations.md
  docs/data-sources/subaccount_user.md
  docs/data-sources/subaccount_users.md
  docs/data-sources/subaccounts.md
  docs/resources/subaccount_role.md
  docs/resources/subaccount_role_collection.md
  internal/provider/datasource_globalaccount.go
  internal/provider/datasource_regions.go
  internal/provider/datasource_subaccount.go
  internal/provider/datasource_subaccount_entitlements.go
  internal/provider/datasource_subaccount_environment_instance.go
  internal/provider/datasource_subaccount_environment_instances.go
  internal/provider/datasource_subaccount_environments.go
  internal/provider/datasource_subaccount_labels.go
  internal/provider/datasource_subaccount_role_collections.go
  internal/provider/datasource_subaccount_roles.go
  internal/provider/datasource_subaccount_service_instances.go
  internal/provider/datasource_subaccount_trust_configuration.go
  internal/provider/datasource_subaccount_trust_configurations.go
  internal/provider/datasource_subaccount_user.go
  internal/provider/datasource_subaccount_users.go
  internal/provider/datasource_subaccounts.go
  internal/provider/resource_subaccount_role.go
  internal/provider/resource_subaccount_role_collection.go
Labels: documentation

#242 feat: test speedup by enabling 'SkipRequestLatency'
  internal/provider/provider_test.go
Labels: ignore-for-release

#245 chore(vscode): add launch configuration for provider debugging
  .vscode/launch.json
Labels: ignore-for-release

#237 chore(workflow): add terraform ecosystem to dependabot
  .github/dependabot.yml
Labels: ignore-for-release

#258 fix(documentation): regenerate to fix mismatch
  docs/index.md
Labels: bug, documentation
