Repository SAP/terraform-provider-btp, pull requests merged in 2023-07, with the labels that each got.

#262 fix(documentation): typo and description of provider.tf
  docs/index.md
  examples/provider/provider.tf
Labels: documentation

#266 fix: Add usage to subaccount resource
  docs/resources/subaccount.md
  internal/provider/fixtures/resource_subaccount.usage_set.yaml
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_test.go
  internal/provider/type_subaccount.go
Labels: bug

#270 fix(documentation): clarify not supported 2FA flow in provider documentation
  docs/index.md
  internal/provider/provider.go
Labels: bug, documentation

#259 fix(facade): transfer global account value when creating subaccount
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
Labels: bug

#264 fix(temp): temporary fix for inconsistent status response for directory deletion
  internal/provider/fixtures/resource_directory.parent_directory.yaml
  internal/provider/resource_directory.go
Labels: bug

#244 feat(resource): Deactivate resource_subaccount_role
  docs/resources/subaccount_role.md
  examples/resources/btp_subaccount_role/import.sh
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_role.go
Labels: enhancement

#246 feat(resource): Deactivate resource_directory_role
  examples/resources/btp_directory_role/import.sh
  internal/provider/provider_test.go
  internal/provider/resource_directory_role.go
Labels: enhancement

#271 feat(resource): add support for service instance resources
  docs/resources/subaccount_service_instance.md
  internal/provider/fixtures/resource_subaccount_service_instance_import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_wo_parameters.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_service_instance_test.go
Labels: enhancement

#276 fix: duplicate role resource in provider.go
  internal/provider/provider.go
Labels: bug

#247 feat: support custom idp login when recording test fixtures
  internal/btpcli/client.go
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: ignore-for-release

#256 feat: Improve matching of replayed interactions during test execution
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
  internal/provider/fixtures/resource_subaccount.yaml
  internal/provider/provider_test.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_environment_instance_test.go
Labels: ignore-for-release

#279 fix: update subaccount with missing fields
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
  internal/provider/resource_subaccount.go
Labels: bug

#283 fix: correct subaccount test recording
  internal/provider/fixtures/resource_subaccount.yaml
Labels: bug

#280 chore(workflows): add workflow to cleanup GH action caches after merge
  .github/workflows/cleanup-action-caches.yml
Labels: ignore-for-release

#286 fix: wrong error message in update of directory resource
  internal/provider/resource_directory.go
Labels: bug, sonar cloud finding

#287 fix: reprioritized FIXME comments
  internal/btpcli/facade_accounts_subscription.go
  internal/btpcli/types/xsuaa_authz/model_user_reference.go
  internal/tfutils/tfutils.go
Labels: ignore-for-release, sonar cloud finding

#290 chore: adjustment of sonar cloud setting
  sonar-project.properties
Labels: ignore-for-release, sonar cloud finding

#289 fix: retest FIXME issues in tests
  internal/provider/datasource_directory_users_test.go
  internal/provider/datasource_globalaccount_role_collection_test.go
  internal/provider/datasource_globalaccount_trust_configuration_test.go
  internal/provider/datasource_subaccount_trust_configuration_test.go
  internal/provider/fixtures/datasource_directory_users.non_existing_idp.yaml
  internal/provider/fixtures/datasource_globalaccount_role_collection.role_collection_not_available.yaml
  internal/provider/fixtures/datasource_globalaccount_trust_configuration.custom_idp_not_existing.yaml
  internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_not_existing.yaml
Labels: ignore-for-release, sonar cloud finding

#282 feat: add resource app subscription
  docs/data-sources/subaccount_app.md
  docs/data-sources/subaccount_apps.md
  docs/data-sources/subaccount_subscription.md
  docs/data-sources/subaccount_subscriptions.md
  docs/resources/subaccount_subscription.md
  internal/btpcli/types/saas_manager_service/time.go
  internal/provider/datasource_subaccount_app_test.go
  internal/provider/datasource_subaccount_apps.go
  internal/provider/datasource_subaccount_apps_test.go
  internal/provider/datasource_subaccount_subscription_test.go
  internal/provider/datasource_subaccount_subscriptions.go
  internal/provider/datasource_subaccount_subscriptions_test.go
  internal/provider/fixtures/datasource_subaccount_apps.yaml
  internal/provider/fixtures/datasource_subaccount_apps_by_id.yaml
  internal/provider/fixtures/datasource_subaccount_subscription_by_id_and_plan.yaml
  internal/provider/fixtures/datasource_subaccount_subscriptions.yaml
  internal/provider/fixtures/resource_subaccount_subscription.yaml
  internal/provider/fixtures/resource_subaccount_subscription_import_error.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_subscription.go
  internal/provider/resource_subaccount_subscription_test.go
Labels: enhancement

#285 feat: add service binding resources and data sources
  docs/data-sources/subaccount_service_binding.md
  docs/data-sources/subaccount_service_bindings.md
  docs/resources/subaccount_service_binding.md
  internal/provider/datasource_subaccount_service_binding_test.go
  internal/provider/datasource_subaccount_service_bindings.go
  internal/provider/datasource_subaccount_service_bindings_test.go
  internal/provider/fixtures/datasource_subaccount_service_binding_by_id.yaml
  internal/provider/fixtures/datasource_subaccount_service_binding_by_name.yaml
  internal/provider/fixtures/datasource_subaccount_service_bindings.yaml
  internal/provider/fixtures/resource_subaccount_service_binding.yaml
  internal/provider/fixtures/resource_subaccount_service_binding_import_error.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_binding_test.go
Labels: enhancement

#301 fix: update service instance failure - resource not found
  internal/btpcli/facade_services_instance.go
  internal/provider/fixtures/resource_subaccount_service_instance_import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_wo_parameters.yaml
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_service_instance_test.go
Labels: bug

#304 feat(resource): support update of subaccount entitlements
  internal/provider/fixtures/resource_subaccount_entitlement.update.yaml
  internal/provider/resource_subaccount_entitlement.go
  internal/provider/resource_subaccount_entitlement_test.go
Labels: enhancement

#306 fix: added missing planmodifier to the computed IDs
  internal/provider/resource_globalaccount_trust_configuration.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_subscription.go
  internal/provider/resource_subaccount_trust_configuration.go
Labels: bug

#310 feat(resource): support update for subaccount_environment_instance
  internal/btpcli/facade_accounts_environment_instance.go
  internal/btpcli/facade_accounts_environment_instance_test.go
  internal/provider/fixtures/resource_subaccount_environment_instance.update.yaml
  internal/provider/fixtures/resource_subaccount_environment_instance.yaml
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_environment_instance_test.go
Labels: enhancement

#317 fix: import of environment instance fails
  internal/provider/fixtures/resource_subaccount_environment_instance.yaml
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_environment_instance_test.go
Labels: bug

#324 chore: refinement of PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#325 docs: docs for new datasources and resources
  docs/data-sources/subaccount_apps.md
  docs/data-sources/subaccount_service_binding.md
  docs/data-sources/subaccount_service_bindings.md
  docs/data-sources/subaccount_service_instance.md
  docs/data-sources/subaccount_service_instances.md
  docs/data-sources/subaccount_service_offering.md
  docs/data-sources/subaccount_service_plan.md
  docs/data-sources/subaccount_subscription.md
  docs/data-sources/subaccount_subscriptions.md
  docs/resources/subaccount_service_binding.md
  docs/resources/subaccount_service_instance.md
  docs/resources/subaccount_subscription.md
  internal/provider/datasource_subaccount_apps.go
  internal/provider/datasource_subaccount_service_binding.go
  internal/provider/datasource_subaccount_service_bindings.go
  internal/provider/datasource_subaccount_service_instance.go
  internal/provider/datasource_subaccount_service_instances.go
  internal/provider/datasource_subaccount_service_offering.go
  internal/provider/datasource_subaccount_service_plan.go
  internal/provider/datasource_subaccount_subscription.go
  internal/provider/datasource_subaccount_subscriptions.go
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_subscription.go
Labels: documentation

#327 docs: align error message punctuation to Terraform best practices
  internal/provider/datasource_whoami.go
  internal/provider/resource_directory_role_collection_assignment.go
  internal/provider/resource_directory_role_collection_assignment_test.go
  internal/provider/resource_globalaccount_role_collection_assignment.go
  internal/provider/resource_globalaccount_role_collection_assignment_test.go
  internal/provider/resource_subaccount_role_collection_assignment.go
  internal/provider/resource_subaccount_role_collection_assignment_test.go
Labels: documentation

#321 fix: polling for service binding (delete)
  internal/provider/fixtures/resource_subaccount_service_binding.yaml
  internal/provider/fixtures/resource_subaccount_service_binding_import_error.yaml
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_binding_test.go
Labels: bug

#318 fix: polling for directories and entitlements
  .github/workflows/test.yml
  docs/resources/subaccount_entitlement.md
  internal/provider/fixtures/resource_subaccount.yaml
  internal/provider/fixtures/resource_subaccount_change_to_used_for_production.yaml
  internal/provider/fixtures/resource_subaccount_entitlement.amount_set.yaml
  internal/provider/fixtures/resource_subaccount_entitlement.no_amount.yaml
  internal/provider/fixtures/resource_subaccount_entitlement.update.yaml
  internal/provider/fixtures/resource_subaccount_used_for_production.yaml
  internal/provider/resource_directory.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_entitlement.go
  internal/provider/resource_subaccount_entitlement_test.go
  internal/provider/type_subaccount_entitlement.go
Labels: bug

#329 fix: missing field in datasources for entitlements
  docs/data-sources/directory_entitlements.md
  docs/data-sources/globalaccount_entitlements.md
  docs/data-sources/subaccount_entitlements.md
  internal/provider/datasource_directory_entitlements.go
  internal/provider/datasource_globalaccount_entitlements.go
  internal/provider/datasource_subaccount_entitlements.go
Labels: bug

#330 fix: provider version in useragent
  internal/version/version.go
Labels: bug

#331 fix(docs): provider version
  docs/index.md
  examples/provider/provider.tf
Labels: documentation

#333 docs: fix for wrong format of tables in terraform registry
  docs/data-sources/globalaccount.md
  docs/data-sources/subaccount_service_binding.md
  docs/data-sources/subaccount_service_offerings.md
  docs/resources/directory.md
  docs/resources/subaccount_service_binding.md
  internal/provider/datasource_globalaccount.go
  internal/provider/datasource_globalaccount_resource_provider.go
  internal/provider/datasource_globalaccount_resource_providers.go
  internal/provider/datasource_subaccount_service_binding.go
  internal/provider/datasource_subaccount_service_offerings.go
  internal/provider/resource_directory.go
  internal/provider/resource_subaccount_service_binding.go
Labels: documentation

#339 fix(resource): fix schema and add tests for resource provider
  docs/resources/globalaccount_resource_provider.md
  internal/btpcli/facade_accounts_resource_provider.go
  internal/btpcli/facade_accounts_resource_provider_test.go
  internal/btpcli/types/provisioning/resource_provider.go
  internal/provider/datasource_globalaccount_resource_provider.go
  internal/provider/datasource_globalaccount_resource_provider_test.go
  internal/provider/datasource_globalaccount_resource_providers.go
  internal/provider/datasource_globalaccount_resource_providers_test.go
  internal/provider/fixtures/datasource_globalaccount_resource_provider.yaml
  internal/provider/fixtures/datasource_globalaccount_resource_providers.yaml
  internal/provider/fixtures/resource_globalaccount_resource_provider.create.yaml
  internal/provider/resource_globalaccount_resource_provider.go
  internal/provider/resource_globalaccount_resource_provider_test.go
  internal/provider/type_globalaccount_resource_provider.go
Labels: bug

#340 chore: add stale handling for issues and prs
  .github/workflows/cleanup-action-caches.yml
  .github/workflows/stale-handling.yml
Labels: github_actions, ignore-for-release

#343 feat(resource): support update of "btp_globalaccount_resource_provider"
  internal/btpcli/facade_accounts_resource_provider.go
  internal/btpcli/facade_accounts_resource_provider_test.go
  internal/provider/fixtures/resource_globalaccount_resource_provider.update.yaml
  internal/provider/resource_globalaccount_resource_provider.go
  internal/provider/resource_globalaccount_resource_provider_test.go
Labels: enhancement

#347 chore: refine bug issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ignore-for-release

#348 chore: adjust goreleaser.yaml for release note creation
  .goreleaser.yml
Labels: ignore-for-release

#350 fix(btp_subaccount_roles): mapping of role names
  internal/provider/datasource_directory_roles.go
  internal/provider/datasource_globalaccount_roles.go
  internal/provider/datasource_subaccount_roles.go
Labels: bug

#352 fix: handling of errors for services, subscriptions and bindings
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_subscription.go
Labels: bug
