Repository SAP/terraform-provider-btp, pull requests merged in 2023-11, with the labels that each got.

#516 docs: switch to release 0.6.0 for provider documentation
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
Labels: documentation, ignore-for-release

#513 feat: remove state in case of 404 errors to enable recreation
  internal/provider/fixtures/resource_subaccount_trust_configuration.error_notfound.yaml
  internal/provider/helper.go
  internal/provider/helper_time.go
  internal/provider/resource_subaccount_trust_configuration.go
  internal/provider/resource_subaccount_trust_configuration_test.go
Labels: enhancement

#518 feat: handling of "not found" resources in READ operations
  internal/provider/fixtures/resource_subaccount_trust_configuration.error_notfound.yaml
  internal/provider/helper.go
  internal/provider/resource_directory.go
  internal/provider/resource_directory_entitlement.go
  internal/provider/resource_directory_role_collection.go
  internal/provider/resource_globalaccount_resource_provider.go
  internal/provider/resource_globalaccount_role_collection.go
  internal/provider/resource_globalaccount_trust_configuration.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_entitlement.go
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_role_collection.go
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_subscription.go
  internal/provider/resource_subaccount_trust_configuration_test.go
Labels: enhancement, dependencies

#521 fix: nil pointer error creation of service instance
  internal/btpcli/facade_services_instance.go
Labels: bug, dependencies

#522 fix: renamed provider config parameter for consistency
  docs/index.md
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: bug, documentation, breaking-change

#525 chore: prep release 0.6.0-beta2
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
Labels: documentation, enhancement, ignore-for-release

#526 fix: adapt to command changes from XSUAA-3964
  internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
  internal/provider/resource_subaccount_trust_configuration.go
  internal/provider/resource_subaccount_trust_configuration_test.go
Labels: btpcli

#527 feat: security_settings resource
  docs/data-sources/globalaccount_security_settings.md
  docs/data-sources/subaccount_security_settings.md
  docs/resources/globalaccount_security_settings.md
  docs/resources/subaccount_security_settings.md
  examples/data-sources/btp_globalaccount_security_settings/data-source.tf
  examples/data-sources/btp_subaccount_security_settings/data-source.tf
  examples/resources/btp_globalaccount_security_settings/resource.tf
  examples/resources/btp_subaccount_security_settings/resource.tf
  internal/btpcli/facade_security.go
  internal/btpcli/facade_security_settings.go
  internal/btpcli/facade_security_settings_test.go
  internal/btpcli/types/xsuaa_settings/binding.go
  internal/btpcli/types/xsuaa_settings/links_settings.go
  internal/btpcli/types/xsuaa_settings/saml_config_settings_resp.go
  internal/btpcli/types/xsuaa_settings/saml_key.go
  internal/btpcli/types/xsuaa_settings/tenant_settings_resp.go
  internal/btpcli/types/xsuaa_settings/token_policy_settings_resp.go
  internal/provider/datasource_globalaccount_security_settings.go
  internal/provider/datasource_globalaccount_security_settings_test.go
  internal/provider/datasource_subaccount_security_settings.go
  internal/provider/datasource_subaccount_security_settings_test.go
  internal/provider/fixtures/datasource_globalaccount_security_settings.yaml
  internal/provider/fixtures/datasource_subaccount_security_settings.by_id.yaml
  internal/provider/fixtures/resource_globalaccount_security_settings.complete.yaml
  internal/provider/fixtures/resource_subaccount_security_settings.complete.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_globalaccount_security_settings.go
  internal/provider/resource_globalaccount_security_settings_test.go
  internal/provider/resource_subaccount_security_settings.go
  internal/provider/resource_subaccount_security_settings_test.go
  internal/provider/type_globalaccount_security_settings.go
  internal/provider/type_subaccount_security_settings.go
  internal/tfutils/tfutils.go
  internal/tfutils/tfutils_test.go
Labels: enhancement

#534 docs: update get started
  docs/index.md
  internal/provider/provider.go
  templates/index.md.tmpl
Labels: documentation

#543 chore: update issue template for bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement, ignore-for-release

#540 feat: enhance dev container to enable remote state configuration
  .devcontainer/default_remote/devcontainer.json
  .devcontainer/withenvfile_remote/devcontainer.json
  DEVELOPER.md
  assets/credentials.tfrc.json.txt
Labels: enhancement

#532 ci: Terraform Integration Landscape Setup
  integration/README.md
  integration/main.tf
  integration/provider.tf
  integration/variables.tf
Labels: enhancement, test-setup

#545 fix: deletion of subaccounts under managed directories
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
  internal/provider/datasource_subaccount_entitlements.go
  internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.full_config.yaml
  internal/provider/fixtures/resource_subaccount.used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.yaml
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_entitlement.go
  internal/provider/type_subaccount.go
  internal/provider/type_subaccount_entitlement.go
Labels: bug

#549 docs: refine origin description
  docs/data-sources/directory_user.md
  docs/data-sources/directory_users.md
  docs/data-sources/globalaccount_user.md
  docs/data-sources/globalaccount_users.md
  docs/data-sources/subaccount_user.md
  docs/data-sources/subaccount_users.md
  docs/resources/directory_role_collection_assignment.md
  docs/resources/globalaccount_role_collection_assignment.md
  docs/resources/subaccount_role_collection_assignment.md
  internal/provider/datasource_directory_user.go
  internal/provider/datasource_directory_users.go
  internal/provider/datasource_globalaccount_user.go
  internal/provider/datasource_globalaccount_users.go
  internal/provider/datasource_subaccount_user.go
  internal/provider/datasource_subaccount_users.go
  internal/provider/resource_directory_role_collection_assignment.go
  internal/provider/resource_globalaccount_role_collection_assignment.go
  internal/provider/resource_subaccount_role_collection_assignment.go
Labels: documentation, ignore-for-release

#548 feat: Directories Datasource
  docs/data-sources/directories.md
  internal/btpcli/facade_accounts_global_account.go
  internal/provider/datasource_directories.go
  internal/provider/datasource_directories_test.go
  internal/provider/datasource_directory.go
  internal/provider/fixtures/datasource_directories.all.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/type_directory.go
Labels: enhancement
