Repository SAP/terraform-provider-btp, pull requests merged in 2023-08, with the labels that each got.

#354 fix: error handling of entitlement polling
  internal/provider/resource_subaccount_entitlement.go
Labels: bug

#355 docs: enhance provider setup documentation
  docs/index.md
  internal/provider/provider.go
Labels: bug

#357 feat: Add fixture drift detection to github action for tests
  .github/scripts/fixtureDriftDetect.sh
  .github/workflows/test.yml
Labels: enhancement, ignore-for-release

#362 feat: Add fixture record/replay log messages
  internal/provider/provider_test.go
Labels: enhancement, ignore-for-release

#375 fix(sonar): Reduce complexity of internal/tfutils/tfutils.go
  internal/tfutils/tfutils.go
Labels: bug

#377 chore: remove copied state.go file from sonar checks
  sonar-project.properties
Labels: sonar cloud finding

#382 fix: env instance parameters classification
  docs/resources/subaccount_environment_instance.md
  internal/provider/resource_subaccount_environment_instance.go
Labels: bug, documentation

#383 fix: Reduce complexity of facade_accounts_entitlement.go
  internal/btpcli/facade_accounts_entitlement.go
Labels: sonar cloud finding

#384 fix: extend timeout for service instance and env instance
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_service_instance.go
Labels: enhancement

#387 fix: workaround for service instance creation
  internal/btpcli/facade_services_instance.go
  internal/provider/fixtures/resource_subaccount_service_instance_import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_wo_parameters.yaml
Labels: bug

#386 docs: correction of environment instance sample
  docs/resources/subaccount_environment_instance.md
  examples/resources/btp_subaccount_environment_instance/resource.tf
Labels: documentation

#394 chore: golang update
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  README.md
  go.mod
  go.sum
Labels: dependencies, ignore-for-release
