Repository SAP/terraform-provider-btp, pull requests merged in 2023-10, with the labels that each got.

#452 chore(dependency): updated test matrix for supported Terraform versions
  .github/workflows/test.yml
Labels: dependencies

#453 chore: GH Action for SBOM creation
  .github/workflows/sbom-creation.yml
Labels: github_actions, ignore-for-release

#464 chore: refine sonar setting for beta resources
  internal/btpcli/types/cis_entitlements/time.go
  internal/provider/provider.go
  sonar-project.properties
Labels: ignore-for-release, sonar cloud finding

#459 feat(btpcli): add support for passcode auth
  docs/index.md
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/provider/provider.go
Labels: enhancement

#469 fix: change FIXME to TODO
  internal/btpcli/client.go
Labels: ignore-for-release, sonar cloud finding

#474 fix: error handling of non-updateable fields of directory
  internal/provider/fixtures/resource_directory.error_change_features.yaml
  internal/provider/resource_directory.go
  internal/provider/resource_directory_test.go
Labels: bug

#478 fix: sonar cloud code smell - error message header
  internal/provider/resource_directory.go
Labels: sonar cloud finding

#481 chore: remove version pinning of TF CLI in devcontainer
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
Labels: dependencies, ignore-for-release

#493 fix: sonar cloud finding
  internal/provider/provider.go
Labels: ignore-for-release, sonar cloud finding

#494 fix: handling of labels on subaccount and directory
  internal/provider/fixtures/resource_directory.error_change_features.yaml
  internal/provider/fixtures/resource_directory.full_config.yaml
  internal/provider/fixtures/resource_directory.with_features.yaml
  internal/provider/fixtures/resource_directory.yaml
  internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.full_config.yaml
  internal/provider/fixtures/resource_subaccount.used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.yaml
  internal/provider/resource_directory.go
  internal/provider/resource_directory_test.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_test.go
Labels: bug, breaking-change

#496 fix: remove unused code for logout
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/btpcli/clienttypes_test.go
Labels: bug

#498 fix: remove workarounds from service instance creation
  internal/btpcli/facade_services_instance.go
  internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.wo_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
  internal/provider/resource_subaccount_service_instance.go
Labels: bug, dependencies

#501 chore: refine sonar settings for generated types from platform APIs
  sonar-project.properties
Labels: ignore-for-release, sonar cloud finding

#502 chore: refine sonar setting, excluded directories for types
  sonar-project.properties
Labels: ignore-for-release, sonar cloud finding

#505 fix: handling of trust configuration for SAP default idp
  internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
  internal/provider/resource_subaccount_trust_configuration.go
  internal/provider/resource_subaccount_trust_configuration_test.go
Labels: bug
