Repository SAP/terraform-provider-btp, pull requests merged in 2023-09, with the labels that each got.

#397 fix: nil pointer exception in subaccounts entitlement read
  internal/provider/resource_subaccount_entitlement.go
Labels: bug

#401 feat: configurable timeouts
  docs/resources/subaccount_environment_instance.md
  docs/resources/subaccount_service_instance.md
  examples/resources/btp_subaccount_environment_instance/resource.tf
  examples/resources/btp_subaccount_service_instance/resource.tf
  go.mod
  go.sum
  internal/provider/datasource_subaccount_environment_instance.go
  internal/provider/datasource_subaccount_service_instance.go
  internal/provider/fixtures/resource_subaccount_environment_instance.with_timeout.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_environment_instance_test.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_service_instance_test.go
  internal/provider/type_subaccount_environment_instance.go
  internal/provider/type_subaccount_service_instance.go
  internal/tfutils/tfutils.go
Labels: enhancement

#403 fix: code formatting
  docs/resources/directory.md
  docs/resources/subaccount_environment_instance.md
  docs/resources/subaccount_service_instance.md
  examples/resources/btp_directory/resource.tf
  examples/resources/btp_subaccount_environment_instance/resource.tf
  examples/resources/btp_subaccount_service_instance/resource.tf
Labels: bug, ignore-for-release

#404 fix: Only add planName to subscribe request if it's not empty
  internal/btpcli/facade_accounts_subaccount.go
Labels: enhancement

#406 feat: support login with id token
  docs/index.md
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/provider/provider.go
Labels: enhancement, btpcli

#411 chore: preparation of version 0.4.0
  docs/index.md
  examples/provider/provider.tf
  internal/provider/provider.go
Labels: documentation, ignore-for-release

#414 feat: add app name to data sources for roles
  docs/data-sources/directory_roles.md
  docs/data-sources/globalaccount_roles.md
  docs/data-sources/subaccount_roles.md
  internal/provider/datasource_directory_roles.go
  internal/provider/datasource_directory_roles_test.go
  internal/provider/datasource_globalaccount_roles.go
  internal/provider/datasource_globalaccount_roles_test.go
  internal/provider/datasource_subaccount_roles.go
  internal/provider/datasource_subaccount_roles_test.go
  internal/provider/fixtures/datasource_directory_roles.not_security_enabled.yaml
  internal/provider/fixtures/datasource_directory_roles.yaml
  internal/provider/fixtures/datasource_globalaccount_roles.yaml
  internal/provider/fixtures/datasource_subaccount_roles.yaml
Labels: enhancement

#420 test: re-activating tests for resource_globalaccount_trust_configuration
  internal/provider/fixtures/resource_globalaccount_trust_configuration.full_spec.yaml
  internal/provider/fixtures/resource_globalaccount_trust_configuration.invalid_origin.yaml
  internal/provider/fixtures/resource_globalaccount_trust_configuration.yaml
  internal/provider/resource_globalaccount_trust_configuration_test.go
Labels: enhancement

#419 docs: add information about SAP Universal ID logon
  docs/index.md
  templates/index.md.tmpl
Labels: documentation

#422 fix: sonar cloud finding - number of function parameters
  internal/btpcli/facade_accounts_entitlement.go
  internal/btpcli/facade_accounts_entitlement_test.go
  internal/provider/resource_directory_entitlement.go
Labels: ignore-for-release, sonar cloud finding

#424 feat: subscription with empty plan name
  internal/btpcli/facade_accounts_subaccount.go
  internal/btpcli/facade_accounts_subaccount_test.go
Labels: enhancement

#436 feat: improve id token login
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: enhancement

#430 docs: sample for creation of kyma env instance
  docs/resources/subaccount_environment_instance.md
  examples/resources/btp_subaccount_environment_instance/resource.tf
Labels: documentation

#439 chore: upgrade dependencies
  go.mod
  go.sum
Labels: dependencies, go, ignore-for-release

#441 chore: pin Terraform CLI version to 1.5.x
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  .github/workflows/test.yml
Labels: dependencies, ignore-for-release

#444 feat: support update of subaccount trust configurations
  docs/data-sources/subaccount_trust_configuration.md
  docs/data-sources/subaccount_trust_configurations.md
  docs/resources/subaccount_trust_configuration.md
  internal/btpcli/facade_security_trust.go
  internal/btpcli/facade_security_trust_test.go
  internal/btpcli/types/xsuaa_trust/trust_configuration_response_object.go
  internal/provider/datasource_subaccount_trust_configuration.go
  internal/provider/datasource_subaccount_trust_configurations.go
  internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_exists.yaml
  internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_not_existing.yaml
  internal/provider/fixtures/datasource_subaccount_trust_configuration.default.yaml
  internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_exists.yaml
  internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_not_existing.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
  internal/provider/resource_globalaccount_trust_configuration.go
  internal/provider/resource_subaccount_trust_configuration.go
  internal/provider/resource_subaccount_trust_configuration_test.go
  internal/provider/type_subaccount_trust_configuration.go
  internal/tfutils/tfutils.go
Labels: enhancement
