Repository SAP/terraform-provider-btp, pull requests merged in 2024-02, with the labels that each got.

#693 docs: improvement of env instance for CF
  docs/resources/subaccount_environment_instance.md
  examples/resources/btp_subaccount_environment_instance/resource.tf
Labels: documentation

#697 chore: regression setup update
  regression-test/README.md
  regression-test/main.tf
  regression-test/variables.tf
Labels: github_actions, ignore-for-release

#699 chore: fix regression setup
  regression-test/main.tf
Labels: github_actions, ignore-for-release, test-setup

#700 chore: prep release 1.0.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: documentation, ignore-for-release

#704 chore: pin GA version for regression
  .github/release.yml
  regression-test/provider.tf
Labels: ignore-for-release, test-setup

#710 chore: Upgrade Go version to 1.22
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  README.md
  go.mod
  go.sum
Labels: dependencies, ignore-for-release

#712 fix: increase test timeout
  Makefile
Labels: ignore-for-release

#716 fix: code quality checks
  internal/provider/provider.go
  internal/provider/resource_directory.go
Labels: ignore-for-release, sonar cloud finding

#719 fix: go version - regression-schema-test
  .github/workflows/schema-regression-test.yml
Labels: github_actions, ignore-for-release

#721 feat: Support show-hierarchy on global Account
  docs/data-sources/globalaccount_with_hierarchy.md
  internal/btpcli/facade_accounts_global_account.go
  internal/btpcli/types/cis/subaccount_response_object.go
  internal/provider/datasource_globalaccount_with_hierarchy.go
  internal/provider/datasource_globalaccount_with_hierarchy_test.go
  internal/provider/fixtures/datasource_globalaccount_with_hierarchy.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/type_directoryHierarchy.go
  internal/provider/type_globalaccount_hierarchy.go
  internal/provider/type_subaccountHierarchy.go
  templates/data-sources/globalaccount_with_hierarchy.md.tmpl
Labels: enhancement

#726 fix: sonar cloud issue naming convention
  internal/provider/datasource_globalaccount_with_hierarchy.go
Labels: ignore-for-release, sonar cloud finding

#725 chore: Initial integration workflow
  .github/workflows/integration-test.yml
Labels: github_actions, ignore-for-release
