Repository SAP/terraform-provider-btp, pull requests merged in 2024-04, with the labels that each got.

#762 chore: release-120 fix fix-regression-test version
  regression-test/provider.tf
Labels: ignore-for-release

#763 docs: update copyright
  README.md
Labels: documentation, ignore-for-release

#771 fix: transfer human readable error message from service broker
  internal/provider/resource_subaccount_service_instance.go
Labels: bug

#772 chore: version cleanup of TF, inclusion of version 1.8.x
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/test.yml
Labels: dependencies, github_actions, ignore-for-release

#769 docs: improve drift and import description
  docs/index.md
  guides/DRIFTDETECTION.md
  guides/IMPORT.md
  templates/index.md.tmpl
Labels: documentation

#773 chore: set tf docs plugin version to 0.18.0
  main.go
Labels: dependencies, ignore-for-release

#775 docs: regenerate docs with updated plugin
  docs/data-sources/directory.md
  docs/data-sources/directory_entitlements.md
  docs/data-sources/directory_labels.md
  docs/data-sources/directory_roles.md
  docs/data-sources/directory_users.md
  docs/data-sources/globalaccount.md
  docs/data-sources/globalaccount_roles.md
  docs/data-sources/globalaccount_security_settings.md
  docs/data-sources/globalaccount_trust_configuration.md
  docs/data-sources/globalaccount_trust_configurations.md
  docs/data-sources/globalaccount_users.md
  docs/data-sources/globalaccount_with_hierarchy.md
  docs/data-sources/subaccount_labels.md
  docs/data-sources/subaccount_roles.md
  docs/data-sources/subaccount_security_settings.md
  docs/data-sources/subaccount_trust_configuration.md
  docs/data-sources/subaccount_trust_configurations.md
  docs/data-sources/subaccount_users.md
  docs/resources/directory.md
  docs/resources/directory_entitlement.md
  docs/resources/directory_role_collection.md
  docs/resources/globalaccount_resource_provider.md
  docs/resources/globalaccount_role_collection.md
  docs/resources/globalaccount_security_settings.md
  docs/resources/globalaccount_trust_configuration.md
  docs/resources/subaccount.md
  docs/resources/subaccount_entitlement.md
  docs/resources/subaccount_environment_instance.md
  docs/resources/subaccount_role_collection.md
  docs/resources/subaccount_security_settings.md
  docs/resources/subaccount_trust_configuration.md
  main.go
Labels: documentation, dependencies, ignore-for-release

#782 docs: new guide for sensitive data (service instance parameters)
  .vscode/settings.json
  README.md
  assets/plan_change_sensitive.png
  assets/plan_create_sensitive.png
  assets/tfplan_json_sensitive.png
  guides/SENSITIVEDATA.md
Labels: documentation

#780 fix: state handling for service instance creation or update fails
  internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.sharing_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_conf_changed.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_enabled.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.wo_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
  internal/provider/resource_subaccount_service_instance.go
Labels: bug

#787 docs: fix issue with drifted documentation due to terraform-docs fix in version 0.19.1
  docs/data-sources/directory.md
  docs/data-sources/directory_labels.md
  docs/data-sources/directory_roles.md
  docs/data-sources/directory_users.md
  docs/data-sources/globalaccount.md
  docs/data-sources/globalaccount_roles.md
  docs/data-sources/globalaccount_security_settings.md
  docs/data-sources/globalaccount_trust_configuration.md
  docs/data-sources/globalaccount_trust_configurations.md
  docs/data-sources/globalaccount_users.md
  docs/data-sources/globalaccount_with_hierarchy.md
  docs/data-sources/subaccount_labels.md
  docs/data-sources/subaccount_roles.md
  docs/data-sources/subaccount_security_settings.md
  docs/data-sources/subaccount_trust_configuration.md
  docs/data-sources/subaccount_trust_configurations.md
  docs/data-sources/subaccount_users.md
  docs/resources/directory.md
  docs/resources/directory_entitlement.md
  docs/resources/directory_role_collection.md
  docs/resources/globalaccount_resource_provider.md
  docs/resources/globalaccount_role_collection.md
  docs/resources/globalaccount_security_settings.md
  docs/resources/globalaccount_trust_configuration.md
  docs/resources/subaccount.md
  docs/resources/subaccount_entitlement.md
  docs/resources/subaccount_environment_instance.md
  docs/resources/subaccount_role_collection.md
  docs/resources/subaccount_security_settings.md
  docs/resources/subaccount_trust_configuration.md
Labels: documentation, ignore-for-release

#788 docs: issue 784
  docs/data-sources/subaccount_subscriptions.md
  internal/provider/datasource_subaccount_subscriptions.go
Labels: bug, documentation
