Repository SAP/terraform-provider-btp, pull requests merged in 2024-12, with the labels that each got.

#971 chore: update Terraform test matrix
  .github/workflows/test.yml
Labels: test-setup

#974 fix: remove terraform 1.10 from test matrix
  .github/workflows/test.yml
Labels: bug

#979 chore: Fix Documentation
  docs/data-sources/subaccount_entitlements.md
  internal/provider/datasource_subaccount_entitlements.go
Labels: documentation

#982 chore: update Go dependencies
  go.mod
  go.sum
Labels: dependencies, go, ignore-for-release
