Repository SAP/terraform-provider-btp, pull requests merged in 2024-03, with the labels that each got.

#727 feat: Get subaccount data source according to subdomain and region
  docs/data-sources/subaccount.md
  internal/provider/datasource_subaccount.go
  internal/provider/datasource_subaccount_test.go
  internal/provider/fixtures/datasource_subaccount.err_invalid_subdomain.yaml
  internal/provider/fixtures/datasource_subaccount_by_subdomain.yaml
Labels: enhancement

#730 fix: Generalised the custom IDP for the tests
  internal/provider/fixtures/resource_globalaccount_trust_configuration.complete.yaml
  internal/provider/fixtures/resource_globalaccount_trust_configuration.invalid_idp.yaml
  internal/provider/fixtures/resource_globalaccount_trust_configuration.minimal.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
  internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
  internal/provider/resource_globalaccount_trust_configuration_test.go
  internal/provider/resource_subaccount_trust_configuration_test.go
Labels: enhancement, security-idp, test-setup

#745 fix: sonar cloud finding - function complexity
  internal/provider/datasource_subaccount.go
Labels: bug, ignore-for-release, sonar cloud finding

#744 docs: fix parameters for Kyma environment instance
  docs/resources/subaccount_environment_instance.md
  examples/resources/btp_subaccount_environment_instance/resource.tf
Labels: bug, documentation

#751 feat: Ability to Share Service Instances
  docs/resources/subaccount_service_instance.md
  examples/resources/btp_subaccount_service_instance/resource.tf
  internal/btpcli/client.go
  internal/btpcli/facade_services_instance.go
  internal/provider/fixtures/resource_subaccount_service_instance.sharing_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_conf_changed.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_enabled.yaml
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_service_instance_test.go
Labels: documentation, enhancement

#752 chore: refine drift detection
  .github/workflows/schema-regression-test.yml
Labels: github_actions, ignore-for-release, test-setup

#753 docs: add example for subaccount data source
  docs/data-sources/subaccount.md
  examples/data-sources/btp_subaccount/data-source.tf
Labels: documentation

#755 fix: data source service instance sharing
  docs/data-sources/subaccount.md
  docs/data-sources/subaccount_service_plan.md
  docs/data-sources/subaccount_service_plans.md
  examples/data-sources/btp_subaccount/data-source.tf
  internal/btpcli/types/servicemanager/model_service_plan_metadata.go
  internal/provider/datasource_subaccount_service_plan.go
  internal/provider/datasource_subaccount_service_plan_test.go
  internal/provider/datasource_subaccount_service_plans.go
  internal/provider/datasource_subaccount_service_plans_test.go
  internal/provider/fixtures/datasource_subaccount_service_plan.by_id.yaml
  internal/provider/fixtures/datasource_subaccount_service_plan.by_name.yaml
  internal/provider/fixtures/datasource_subaccount_service_plans.all.yaml
  internal/provider/fixtures/datasource_subaccount_service_plans.cloudfoundry.yaml
  internal/provider/fixtures/datasource_subaccount_service_plans.namefilter.yaml
Labels: bug

#758 fix: make binding state response more resillient
  internal/provider/type_subaccount_service_binding.go
Labels: bug
