Repository SAP/terraform-provider-btp, pull requests merged in 2024-08, with the labels that each got.

#874 feat: add retry logic for rate limit for entitlement
  internal/provider/resource_subaccount_entitlement.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_subscription.go
Labels: enhancement

#890 fix: Broken Lint Tests & chore: upgrade of go version
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  README.md
  go.mod
  internal/btpcli/client.go
  internal/btpcli/client_test.go
Labels: bug, ignore-for-release

#891 chore: rework devcontainer setup
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
Labels: dependencies, ignore-for-release

#893 feat: Resource to manage XSUAA Api Credentials
  docs/resources/directory_api_credential.md
  docs/resources/globalaccount_api_credential.md
  docs/resources/subaccount_api_credential.md
  examples/resources/btp_directory_api_credential/resource.tf
  examples/resources/btp_globalaccount_api_credential/resource.tf
  examples/resources/btp_subaccount_api_credential/resource.tf
  examples/resources/certificate.go
  internal/btpcli/facade_security.go
  internal/btpcli/facade_security_api_credential.go
  internal/btpcli/facade_security_api_credential_test.go
  internal/btpcli/types/xsuaa_api/model_api_credential_subaccount.go
  internal/provider/fixtures/resource_directory_api_credential.error_invalid_certificate.yaml
  internal/provider/fixtures/resource_directory_api_credential.read_only_credentials.yaml
  internal/provider/fixtures/resource_directory_api_credential.with_certificate.yaml
  internal/provider/fixtures/resource_directory_api_credential.with_secret.yaml
  internal/provider/fixtures/resource_globalaccount_api_credential.error_invalid_certificate.yaml
  internal/provider/fixtures/resource_globalaccount_api_credential.read_only_credentials.yaml
  internal/provider/fixtures/resource_globalaccount_api_credential.with_certificate.yaml
  internal/provider/fixtures/resource_globalaccount_api_credential.with_secret.yaml
  internal/provider/fixtures/resource_subaccount_api_credential.error_invalid_certificate.yaml
  internal/provider/fixtures/resource_subaccount_api_credential.error_missing_subaccount_id.yaml
  internal/provider/fixtures/resource_subaccount_api_credential.read_only_credentials.yaml
  internal/provider/fixtures/resource_subaccount_api_credential.with_certificate.yaml
  internal/provider/fixtures/resource_subaccount_api_credential.with_secret.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_directory_api_credential.go
  internal/provider/resource_directory_api_credential_test.go
  internal/provider/resource_globalaccount_api_credential.go
  internal/provider/resource_globalaccount_api_credential_test.go
  internal/provider/resource_subaccount_api_credential.go
  internal/provider/resource_subaccount_api_credential_test.go
  internal/provider/type_directory_api_credential.go
  internal/provider/type_globalaccount_api_credential.go
  internal/provider/type_subaccount_api_credential.go
  internal/tfutils/certificate_generator.go
Labels: enhancement

#892 chore: prep opentofu support
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  .github/workflows/compatibility-test.yml
  .github/workflows/schema-regression-test-opentofu.yml
  .github/workflows/test-opentofu.yml
Labels: ignore-for-release, test-setup

#895 chore: Prep Release v1.6.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: ignore-for-release
