Repository SAP/terraform-provider-btp, pull requests merged in 2024-11, with the labels that each got.

#941 chore: Prep works v1.8.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: ignore-for-release

#943 fix: unexpected update of a btp_subaccount_service_binding
  internal/provider/resource_subaccount_service_binding.go
Labels: bug

#951 fix: handling reset of secrets and certificates to NULL in the api-credential resources
  internal/provider/resource_directory_api_credential.go
  internal/provider/resource_globalaccount_api_credential.go
  internal/provider/resource_subaccount_api_credential.go
  internal/provider/type_directory_api_credential.go
  internal/provider/type_globalaccount_api_credential.go
  internal/provider/type_subaccount_api_credential.go
Labels: bug

#950 feat: code improvements based on SonarCloud findings for the Api-Credential Resources
  docs/resources/directory_api_credential.md
  docs/resources/globalaccount_api_credential.md
  docs/resources/subaccount_api_credential.md
  examples/resources/btp_directory_api_credential/resource.tf
  examples/resources/btp_globalaccount_api_credential/resource.tf
  examples/resources/btp_subaccount_api_credential/resource.tf
  examples/resources/certificate.go
  internal/btpcli/facade_security_api_credential.go
  internal/btpcli/facade_security_api_credential_test.go
  internal/btpcli/types/xsuaa_api/model_api_credential_subaccount.go
  internal/provider/resource_directory_api_credential.go
  internal/provider/resource_directory_api_credential_test.go
  internal/provider/resource_globalaccount_api_credential_test.go
  internal/provider/resource_subaccount_api_credential.go
  internal/provider/resource_subaccount_api_credential_test.go
  internal/provider/type_directory_api_credential.go
  internal/provider/type_globalaccount_api_credential.go
  internal/provider/type_subaccount_api_credential.go
  internal/tfutils/certificate_generator.go
  internal/tfutils/certificate_generator_test.go
Labels: refactoring
