Repository SAP/terraform-provider-btp, pull requests merged in 2024-09, with the labels that each got.

#900 docs: upate contribution guidelines
  CONTRIBUTING.md
Labels: documentation, ignore-for-release

#909 fix: link checker
  .lycheeignore
Labels: github_actions, ignore-for-release

#910 fix: added retry logic for reading resource subaccount entitlement
  internal/provider/resource_subaccount_entitlement.go
Labels: bug

#911 chore: Prep works v1.7.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: ignore-for-release
