Repository SAP/terraform-provider-btp, pull requests merged in 2024-07, with the labels that each got.

#852 chore(refactor): code styling
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/btpcli/facade_accounts_entitlement_test.go
  internal/btpcli/facade_accounts_global_account.go
  internal/btpcli/facade_services_instance.go
  internal/provider/datasource_globalaccount_security_settings_test.go
  internal/provider/datasource_globalaccount_test.go
  internal/provider/datasource_globalaccount_with_hierarchy.go
  internal/provider/resource_globalaccount_role_collection_test.go
  internal/provider/resource_subaccount_role_collection_assignment_test.go
  internal/provider/resource_subaccount_role_collection_test.go
  internal/provider/type_globalaccount_hierarchy.go
  internal/provider/type_subaccount.go
Labels: go, ignore-for-release

#856 feat: increased timeout for resource subaccount subscription
  internal/provider/resource_subaccount_subscription.go
Labels: enhancement

#854 fix: check for multiple auth parameters
  internal/provider/provider.go
Labels: bug

#860 chore: terraform fmt
  docs/data-sources/subaccount.md
  docs/resources/directory.md
  docs/resources/directory_entitlement.md
  examples/data-sources/btp_subaccount/data-source.tf
  examples/resources/btp_directory/resource.tf
  examples/resources/btp_directory_entitlement/resource.tf
  integration/main.tf
  integration/variables.tf
  regression-test/variables.tf
Labels: go, ignore-for-release

#857 feat: subaccount service broker
  docs/data-sources/subaccount_service_broker.md
  docs/data-sources/subaccount_service_brokers.md
  docs/resources/subaccount_service_broker.md
  examples/resources/btp_subaccount_service_broker/import.sh
  examples/resources/btp_subaccount_service_broker/resource.tf
  internal/btpcli/facade_services_broker.go
  internal/btpcli/facade_services_broker_test.go
  internal/provider/datasource_subaccount_service_broker.go
  internal/provider/datasource_subaccount_service_broker_test.go
  internal/provider/datasource_subaccount_service_brokers.go
  internal/provider/datasource_subaccount_service_brokers_test.go
  internal/provider/fixtures/datasource_subaccount_service_broker.by_id.yaml
  internal/provider/fixtures/datasource_subaccount_service_brokers.yaml
  internal/provider/fixtures/resource_subaccount_service_broker.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_subaccount_service_broker.go
  internal/provider/resource_subaccount_service_broker_test.go
Labels: enhancement

#861 chore: timeout for test runs
  .github/workflows/test.yml
Labels: ignore-for-release, test-setup

#858 feat: Resource to create roles
  docs/resources/directory_role.md
  docs/resources/globalaccount_role.md
  docs/resources/subaccount_role.md
  internal/btpcli/facade_security_role.go
  internal/btpcli/facade_security_role_test.go
  internal/provider/fixtures/resource_directory_role.error_import.yaml
  internal/provider/fixtures/resource_directory_role.not_security_enabled.yaml
  internal/provider/fixtures/resource_directory_role.update.yaml
  internal/provider/fixtures/resource_directory_role.yaml
  internal/provider/fixtures/resource_globalaccount_role.update.yaml
  internal/provider/fixtures/resource_globalaccount_role.yaml
  internal/provider/fixtures/resource_subaccount_role.error_import.yaml
  internal/provider/fixtures/resource_subaccount_role.update.yaml
  internal/provider/fixtures/resource_subaccount_role.yaml
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_directory_role.go
  internal/provider/resource_directory_role_test.go
  internal/provider/resource_globalaccount_role.go
  internal/provider/resource_globalaccount_role_test.go
  internal/provider/resource_subaccount_role.go
  internal/provider/resource_subaccount_role_test.go
  internal/provider/type_directory_role.go
  sonar-project.properties
Labels: enhancement

#862 chore: Prep Release v1.5.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: documentation, ignore-for-release

#867 fix: removed idp from regression tests
  .github/workflows/schema-regression-test.yml
  regression-test/provider.tf
Labels: github_actions, security-idp

#871 fix: empty placeholders in error message
  internal/provider/datasource_subaccount.go
Labels: bug

#865 feat: add dashboard URL to service instance
  docs/data-sources/subaccount_service_instance.md
  docs/data-sources/subaccount_service_instances.md
  docs/resources/subaccount_service_instance.md
  internal/provider/datasource_subaccount_service_instance.go
  internal/provider/datasource_subaccount_service_instances.go
  internal/provider/fixtures/datasource_subaccount_service_instance.by_id.yaml
  internal/provider/fixtures/datasource_subaccount_service_instance.by_name.yaml
  internal/provider/fixtures/datasource_subaccount_service_instances.all.yaml
  internal/provider/fixtures/datasource_subaccount_service_instances.labelsfilter.yaml
  internal/provider/fixtures/datasource_subaccount_service_instances.namefilter.yaml
  internal/provider/fixtures/datasource_subaccount_service_instances.namefilter_variant.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.creation_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.sharing_error.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_conf_changed.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_enabled.yaml
  internal/provider/fixtures/resource_subaccount_service_instance.wo_parameters.yaml
  internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/type_subaccount_service_instance.go
Labels: enhancement
