Repository SAP/terraform-provider-btp, pull requests merged in 2025-04, with the labels that each got.

#1064 fix: handling drift detection for subscriptions
  internal/provider/helper.go
  internal/provider/provider.go
  internal/provider/resource_directory.go
  internal/provider/resource_directory_api_credential.go
  internal/provider/resource_directory_entitlement.go
  internal/provider/resource_directory_role.go
  internal/provider/resource_directory_role_collection.go
  internal/provider/resource_globalaccount_api_credential.go
  internal/provider/resource_globalaccount_resource_provider.go
  internal/provider/resource_globalaccount_role.go
  internal/provider/resource_globalaccount_role_collection.go
  internal/provider/resource_globalaccount_security_settings.go
  internal/provider/resource_globalaccount_trust_configuration.go
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_api_credential.go
  internal/provider/resource_subaccount_environment_instance.go
  internal/provider/resource_subaccount_role.go
  internal/provider/resource_subaccount_role_collection.go
  internal/provider/resource_subaccount_security_settings.go
  internal/provider/resource_subaccount_service_binding.go
  internal/provider/resource_subaccount_service_broker.go
  internal/provider/resource_subaccount_service_instance.go
  internal/provider/resource_subaccount_subscription.go
  internal/provider/resource_subaccount_trust_configuration.go
Labels: bug

#1067 chore: update linter and fix new findings
  .github/workflows/test.yml
  internal/btpcli/client_test.go
  internal/btpcli/helper.go
  internal/provider/datasource_directory_entitlements_test.go
  internal/provider/datasource_directory_labels_test.go
  internal/provider/datasource_directory_role_collection_test.go
  internal/provider/datasource_directory_role_collections_test.go
  internal/provider/datasource_directory_role_test.go
  internal/provider/datasource_directory_roles_test.go
  internal/provider/datasource_directory_test.go
  internal/provider/datasource_directory_user_test.go
  internal/provider/datasource_directory_users_test.go
  internal/provider/datasource_globalaccount_entitlements_test.go
  internal/provider/datasource_globalaccount_role_collection_test.go
  internal/provider/datasource_globalaccount_role_collections_test.go
  internal/provider/datasource_globalaccount_role_test.go
  internal/provider/datasource_globalaccount_roles_test.go
  internal/provider/datasource_globalaccount_test.go
  internal/provider/datasource_globalaccount_trust_configuration_test.go
  internal/provider/datasource_globalaccount_trust_configurations_test.go
  internal/provider/datasource_globalaccount_user_test.go
  internal/provider/datasource_globalaccount_users_test.go
  internal/provider/datasource_regions_test.go
  internal/provider/datasource_subaccount_entitlements_test.go
  internal/provider/datasource_subaccount_environment_instances_test.go
  internal/provider/datasource_subaccount_environments_test.go
  internal/provider/datasource_subaccount_labels_test.go
  internal/provider/datasource_subaccount_role_collection_test.go
  internal/provider/datasource_subaccount_role_collections_test.go
  internal/provider/datasource_subaccount_role_test.go
  internal/provider/datasource_subaccount_roles_test.go
  internal/provider/datasource_subaccount_test.go
  internal/provider/datasource_subaccount_trust_configuration_test.go
  internal/provider/datasource_subaccount_trust_configurations_test.go
  internal/provider/datasource_subaccount_user_test.go
  internal/provider/datasource_subaccount_users_test.go
  internal/provider/resource_subaccount_test.go
  internal/tfutils/certificate_generator.go
Labels: ignore-for-release, internal

#1070 docs: add limitation for moving subaccounts
  docs/resources/subaccount.md
  guides/MOVESUBACCOUNT.md
  templates/resources/subaccount.md.tmpl
Labels: documentation

#1077 fix(subaccount/subscription): handling of commercial and technical app names
  internal/provider/fixtures/resource_subaccount_subscription.import_error.yaml
  internal/provider/fixtures/resource_subaccount_subscription.yaml
  internal/provider/fixtures/resource_subaccount_subscription_commercialapp_name.yaml
  internal/provider/fixtures/resource_subaccount_subscription_techapp_name.yaml
  internal/provider/fixtures/resource_subaccount_subscription_update.yaml
  internal/provider/fixtures/resource_subaccount_subscription_update_plan.update_error.yaml
  internal/provider/fixtures/resource_subaccount_subscription_with_timeouts.yaml
  internal/provider/resource_subaccount_subscription.go
  internal/provider/resource_subaccount_subscription_test.go
  test/main.tf
Labels: bug

#1080 fix: subaccount error during deletion
  internal/btpcli/facade_accounts_subaccount.go
  internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.full_config.yaml
  internal/provider/fixtures/resource_subaccount.used_for_production.yaml
  internal/provider/fixtures/resource_subaccount.yaml
Labels: bug

#1081 chore: prepare release 1.12.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
Labels: ignore-for-release, internal
