Repository SAP/terraform-provider-btp, pull requests merged in 2025-07, with the labels that each got.

#1134 fix: handling of timeout block for import of subscriptions
  btp/provider/resource_subaccount_subscription.go
  docs/resources/subaccount_subscription.md
Labels: bug

#1142 chore: align login flows to wire protocoll
  btp/provider/datasource_whoami.go
  internal/btpcli/client.go
  internal/btpcli/client_test.go
  internal/btpcli/clienttypes.go
  internal/btpcli/session.go
Labels: btpcli, dependencies

#1146 chore: update Terraform scripts for canary landscape compatibility
  .github/workflows/canary-regression-test.yml
Labels: ignore-for-release, internal

#1147 chore: Prep v1.15.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: ignore-for-release, internal

#1151 chore: prep hotfix release 1.15.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
  integration/provider.tf
Labels: ignore-for-release, internal

#1153 docs: import samples typo and formatting
  docs/resources/directory.md
  docs/resources/directory_entitlement.md
  docs/resources/directory_role.md
  docs/resources/directory_role_collection.md
  docs/resources/globalaccount_role.md
  docs/resources/subaccount_entitlement.md
  docs/resources/subaccount_role.md
  docs/resources/subaccount_role_collection.md
  docs/resources/subaccount_subscription.md
  examples/resources/btp_directory/import.sh
  examples/resources/btp_directory_entitlement/import.sh
  examples/resources/btp_directory_role/import.sh
  examples/resources/btp_directory_role_collection/import.sh
  examples/resources/btp_globalaccount_role/import.sh
  examples/resources/btp_subaccount_entitlement/import.sh
  examples/resources/btp_subaccount_role/import.sh
  examples/resources/btp_subaccount_role_collection/import.sh
  examples/resources/btp_subaccount_subscription/import.sh
Labels: documentation

#1152 fix: validate labels for subaccount
  btp/provider/resource_subaccount.go
  internal/validation/labelvalidator/labelvalidator.go
  internal/validation/labelvalidator/labelvalidator_test.go
Labels: bug
