Repository SAP/terraform-provider-btp, pull requests merged in 2025-05, with the labels that each got.

#1094 chore: Updated Terraform Version for Test Matrix
  .github/workflows/test.yml
Labels: ignore-for-release, test setup, internal

#1099 fix: error message for entitlement status
  internal/provider/resource_subaccount_entitlement.go
Labels: bug

#1100 docs: update of timeline for drift limitation
  guides/DRIFTDETECTION.md
Labels: documentation

#1101 feat: add entitlement error reason to output
  internal/provider/resource_subaccount_entitlement.go
Labels: enhancement

#1106 feat: relax constraint for subdomain naming convention
  docs/resources/subaccount.md
  internal/provider/resource_subaccount.go
  internal/provider/resource_subaccount_test.go
  internal/provider/type_subaccount.go
  templates/resources/subaccount.md.tmpl
Labels: enhancement
